#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

if [ -z "$1" ]
  then
    echo "No argument supplied, please supply a Top Level Domain (e.g. example.com)."
    echo "./get-le example.com user@example.com"
    exit 1
fi

if [ -z "$2" ]
  then
    echo "Please supply your email address"
    echo "./get-le example.com user@example.com"
    exit 1
fi

sudo certbot certonly \
  --manual \
  --preferred-challenges=dns \
  --email $2 \
  --server https://acme-v02.api.letsencrypt.org/directory \
  --agree-tos \
  -d $1 -d *.$1

sudo cp -rfH /etc/letsencrypt/live/$1/fullchain.pem /home/docksal/.docksal/certs/$1.crt
sudo cp -rfH /etc/letsencrypt/live/$1/privkey.pem /home/docksal/.docksal/certs/$1.key
sudo chown -R docksal:docksal /home/docksal/.docksal/certs