#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

if [ -z "$1" ]
  then
    echo "No project user supplied"
    echo ""
    echo "--Example: ./project-user-del USER_NAME"
    echo ""
    exit 1
fi

# Lowercase the name for consistency
USER=$(echo "$1" | tr '[:upper:]' '[:lower:]')

delete_project_user()
{
  # Check if user exists
  if id "$USER" >/dev/null 2>&1; then
    echo-green "Deleting '$USER'"

    # TO DO: prompt for confirmation
    # TO DO: check if the project has sandboxes and delete those users as well
    sudo userdel -f -r $USER
  else
    echo-yellow "There's no user named '$USER'"
  fi
}

delete_project_user
sudo fin cleanup
