#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

if [ -z "$1" ]
  then
    echo "No argument supplied, please supply a user name."
    exit 1
fi

# If top level domain is not given, set a default one
if [ -z "$2" ]; then
  CUSTOMDOMAIN="gtacty.co"
else
  CUSTOMDOMAIN="$2"
fi

# Lowercase the branch name for consistency
BRANCH=$(echo "$1" | tr '[:upper:]' '[:lower:]')
SANDBOX_ROOT="/home"

# if [ "$SANDBOX_ROOT/$BRANCH/.docksal" == "$PWD/.docksal" || [ ! -d $PWD/.docksal ]]; then
if [ ! -d $PWD/.docksal ]; then
  echo-red "Cannot detect project root. Please make sure you run the sandbox command from a Dockal project's root folder."
  exit 1
fi

BRANCH_DIR="$SANDBOX_ROOT/$BRANCH"
GIT_REPOSITORY=$(git config --get remote.origin.url)
BRANCH_ROOT="$BRANCH_DIR/project/$BRANCH"
BRANCH_DOMAIN="$BRANCH.$CUSTOMDOMAIN"
PROJECT_ROOT=$PWD

create_sandbox_user()
{
  if id "$BRANCH" >/dev/null 2>&1; then
    echo-yellow "User $BRANCH exists, go to $BRANCH_DIR"
  else
    echo-green " - Creating user '$BRANCH' using home: '$BRANCH_DIR'"
    sudo adduser --disabled-password --gecos "" --shell /usr/bin/zsh --home $BRANCH_DIR $BRANCH > /dev/null
  fi

  # Make sure the SSH key is in place
  if [ ! -d "$BRANCH_DIR/.ssh" ]; then
    sudo mkdir "$BRANCH_DIR/.ssh"
  fi

  sudo cp -rf /home/docksal/.ssh $BRANCH_DIR > /dev/null
  sudo chown -R $BRANCH:$BRANCH $BRANCH_DIR > /dev/null

  echo-green " - Installing 'Oh My ZSH!'"
  OH_MY_ZSH="https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
  sudo runuser -l $BRANCH -c "cd $BRANCH_DIR; curl -fsSL $OH_MY_ZSH | bash" >/dev/null 2>&1

  echo-green " - Installing SpaceVIM"
  SPACEVIM="https://spacevim.org/install.sh"
  sudo runuser -l $BRANCH -c "cd $BRANCH_DIR; curl -sLf $SPACEVIM | bash" >/dev/null 2>&1

  # Point VIM to use SPACEVIM
  echo-green " - Making sure Vim uses SpaceVIM"
  sudo ln -s $BRANCH_DIR/.SpaceVim $BRANCH_DIR/.vim > /dev/null

  echo-green " - Installing vimproc for interactive command execution in Vim"
  VIMPROC="https://github.com/Shougo/vimproc.vim.git"
  sudo runuser -l $BRANCH -c "cd $BRANCH_DIR; git clone $VIMPROC" >/dev/null 2>&1

  sudo chown -R $BRANCH:$BRANCH $BRANCH_DIR > /dev/null
}

get_repo()
{
  sudo runuser -l $BRANCH -c "cd; mkdir -p $BRANCH_DIR/project"
  sudo runuser -l $BRANCH -c "cd $BRANCH_DIR/project;  git clone $GIT_REPOSITORY $BRANCH"
  sudo chown -R $BRANCH:$BRANCH $BRANCH_DIR > /dev/null
  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; git init" > /dev/null
  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; git branch $BRANCH"
  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; git checkout $BRANCH"

  exists=$(git show-ref refs/heads/$BRANCH)
  if [ -n "$exists" ]; then
    echo 'Branch $BRANCH exists, pulling it..'
    sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; git pull origin $BRANCH"
  fi

  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; git config --global user.email 'you@example.com'"
  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; git config --global user.name '$BRANCH'"
}

initialize_stack()
{
  cd $BRANCH_ROOT
  sudo usermod -aG docker $BRANCH
  sudo cp -rf /home/docksal/.docksal $BRANCH_DIR
  sudo rm -rf $BRANCH_DIR/.docksal/alias
  sudo mkdir $BRANCH_DIR/.docksal/alias
  sudo chown -R $BRANCH:$BRANCH "$BRANCH_DIR/.docksal"

  if [ -f "$BRANCH_ROOT/.docksal/docksal-local.env" ]; then
    sudo rm -rf "$BRANCH_ROOT/.docksal/docksal-local.env"
  fi
  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT/.docksal; echo \"VIRTUAL_HOST=$BRANCH_DOMAIN\" > $BRANCH_ROOT/.docksal/docksal-local.env"

  # Stack initialization
  if [[ $DOCKER_RUNNING == "true" ]]; then
    sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; fin reset -f"
  else
    sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; fin up"
  fi
  echo "Waiting 10s for MySQL to initialize...";
  sleep 10
}

set_public_ip()
{
  ### Set up a public domain with nip.io which also facilitates LetsEncrypt SSL certificates.
  LOCAL_DOCKSAL="$BRANCH_ROOT/.docksal/docksal-local.env"
  sudo rm -rf $LOCAL_DOCKSAL
  # Grab the project root directory name
  project=$(basename $BRANCH_ROOT | sed 's/\./-/g')
  # Wildcard DNS 1
  # vhost="$project.wd1.condurachi.ro"
  vhost="$project.$CUSTOMDOMAIN"
  sudo runuser -l $BRANCH -c "echo \"VIRTUAL_HOST=$vhost\" > $LOCAL_DOCKSAL"
  ##################

  ### Set the right drush alias corresponding to the public domain
  ALIASES_FILE="$BRANCH_ROOT/drush/aliases.drushrc.php"
  if [ -f $ALIASES_FILE ]; then
    sudo rm -rf $ALIASES_FILE
    sudo mkdir -p $BRANCH_ROOT/drush
  fi

  sudo runuser -l $BRANCH -c "echo \"<?php\" > $ALIASES_FILE"
  sudo runuser -l $BRANCH -c "echo \"// @docksal Dev Drush alias\" >> $ALIASES_FILE"
  sudo runuser -l $BRANCH -c "echo '\$aliases[\"dev\"] = array(' >> $ALIASES_FILE"
  sudo runuser -l $BRANCH -c "echo \"  'uri' => '$vhost',\" >> $ALIASES_FILE"
  sudo runuser -l $BRANCH -c "echo \");\" >> $ALIASES_FILE"
  ##################

  sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; fin p start"

  if [ -d "$PROJECT_ROOT/db" ]; then
    cd $PROJECT_ROOT
    echo $PROJECT_ROOT
    if [ -f "$PROJECT_ROOT/db/dump.sql" ]; then
      sudo cp -rf "$PROJECT_ROOT/db" "$BRANCH_ROOT"
      sudo chown -R $BRANCH:$BRANCH "$BRANCH_ROOT/db"
      echo-green "Importing database..."
      sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; fin db import $BRANCH_ROOT/db/*.sql --progress"
    fi
  fi
}

get_ssl() 
{
# If this is not a local server but one with a public IP AND public DOMAIN assigned,
# then generate SSL certificates with LetsEncrypt.org

  # Grab the project root directory name
  project=$(basename $BRANCH_ROOT | sed 's/\./-/g')
  # Wildcard DNS 1
  vhost="$BRANCH_DOMAIN"

  fin p start

# By this point, VIRTUAL_HOST is set to the new domain name
if [ $vhost != *.docksal ]; then
  if [ -f /usr/bin/certbot ]; then
    # Wildcard DNS
    if [ -f "$BRANCH_DIR/.docksal/certs/$CUSTOMDOMAIN.crt" ]; then
      sudo cp -r "$BRANCH_DIR/.docksal/certs/$CUSTOMDOMAIN.crt" "$BRANCH_DIR/.docksal/certs/$vhost.crt"
    fi
    if [ -f "$BRANCH_DIR/.docksal/certs/$CUSTOMDOMAIN.key" ]; then
      sudo cp -r "$BRANCH_DIR/.docksal/certs/$CUSTOMDOMAIN.key" "$BRANCH_DIR/.docksal/certs/$vhost.key"
    fi
    sudo chown -R $BRANCH:$BRANCH $BRANCH_DIR/.docksal

    # Fix DOCROOT variable, hardcoding for now
    DOCROOT=$(cd $BRANCH_ROOT; fin exec 'echo -n $DOCROOT')
    sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; fin p start"
    LOCAL_SETTINGS="$BRANCH_ROOT/$DOCROOT/sites/default/settings.local.php"
    
    if [ -f "$DOCROOT/sites/default/files" ]; then
      sudo cp -r $DOCROOT/sites/default/files $BRANCH_ROOT/$DOCROOT/sites/default
    fi
    sudo chown -R $BRANCH $BRANCH_ROOT

    # Make sure sites/default is writable
    sudo chmod 755 "$BRANCH_ROOT/$DOCROOT/sites/default"

    # If settings.local.php doesn't exist, create it
    if [ ! -f $LOCAL_SETTINGS ]; then
      sudo rm -rf $LOCAL_SETTINGS
      sudo runuser -l $BRANCH -c "echo \"<?php\" > $LOCAL_SETTINGS"
      sudo runuser -l $BRANCH -c "echo '\$base_url = \"https://$vhost\";' >> $LOCAL_SETTINGS"
    fi

    echo-green "LetsEncrypt SSL certificates installed"

    sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT; fin p start"

    echo-green "Clearing website caches"
    sudo runuser -l $BRANCH -c "cd $BRANCH_ROOT/$DOCROOT; fin drush cr"
  else
    echo-yellow "Certbot NOT installed."
  fi
fi
}

echo ""
echo-green "1. Create sandbox user based on given branch: '$BRANCH'"
echo-green "   Making sure Docksal is running"
fin system start
create_sandbox_user

echo ""
echo-green "2. Get repository branch"
get_repo

echo ""
echo-green "3. Initializing stack..."
initialize_stack

echo ""
echo-green "4. Set public IP and domain for branch..."
set_public_ip

echo ""
echo-green "5. Copying SSL certificates if they exist in '/home/docksal/.docksal/certs'..."
get_ssl

# Make sure everything is owned by the branch
sudo chown -R $BRANCH:$BRANCH $BRANCH_DIR
